pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Instalando dependências na raiz do projeto...'
                // O package.json está na raiz, então 'npm install' é executado aqui.
                bat "npm install"
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Executando os testes...'
                // Este passo exige que o package.json tenha o caminho correto para jest.setup.js
                // Ex: "setupFiles": ["<rootDir>/backend/fake_sql/jest.setup.js"]
                bat "npm test"
            }
        }

        stage('Build Application') {
            steps {
                echo 'Compilando a aplicação...'
                bat "npm run build"
            }
        }

        stage('Start Application') {
            steps {
                echo 'Iniciando o servidor backend...'
                bat "npm start"
            }
        }

        stage('Security Analysis') {
            steps {
                echo 'Executando análise de segurança com npm audit na raiz...'
                bat "npm audit"
            }
        }
    }
}